"""Added CVE _ID column to scan table

Revision ID: 4aab26b87538
Revises: e9225ca1d851
Create Date: 2024-03-16 16:43:04.674821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4aab26b87538'
down_revision = 'e9225ca1d851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cve_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cve_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vulnerability_score', sa.Float(), nullable=True))
        batch_op.drop_column('cve_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cve_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('vulnerability_score')
        batch_op.drop_column('cve_description')
        batch_op.drop_column('cve_id')

    # ### end Alembic commands ###
