"""Added CVE seperate table to be used for all cve's being saved

Revision ID: b17749656de0
Revises: 4aab26b87538
Create Date: 2024-03-16 16:53:29.041859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17749656de0'
down_revision = '4aab26b87538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('vulnerability_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('cve_description')
        batch_op.drop_column('cve_id')
        batch_op.drop_column('vulnerability_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vulnerability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cve_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cve_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.drop_table('cve')
    # ### end Alembic commands ###
