"""CVE DATA ADDED

Revision ID: e9225ca1d851
Revises: eb51b3bc64da
Create Date: 2024-03-14 16:29:39.811714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9225ca1d851'
down_revision = 'eb51b3bc64da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cve_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('cve_data')

    # ### end Alembic commands ###
